---
title: "`r paste('World', params$mammals_family, 'analysis')`"
author: "Jane Doe"
date: "`r format(Sys.time(), '%Y/%m/%d')`"
format:
  html:
    self_contained: true
    fig_caption: yes
    # theme: united
    toc: true
    toc_float:
      collapsed: true
params: 
  mammals_family: "Ursidae"
execute:
  echo: true
  eval: true
  message: false
  fig-width: 7
  fig-height: 7
knitr:
  opts_chunk: 
    collapse: true
    out-width: "100%"
    dpi: 300
---


# Set up project

```{r}
#| label: 'setup'
#| message: false

## Load project ----
devtools::load_all()
```


# Data acquisition

```{r}
#| label: 'download-data'
#| eval: false

## Download data ----
dl_wildfinder_data()
```

# Data importation

## Mammals species list

```{r}
#| label: 'read-data-1'

## Import species list ----
sp_list  <- read_sp_list(here::here("data", "wildfinder", 
                                    "wildfinder-mammals_list.csv"))
```

```{r}
#| label: 'print-data-1'
#| echo: false

knitr::kable(head(sp_list), caption = "Content of the wildfinder-mammals_list file")
```


## Ecoregions list

```{r}
#| label: 'read-data-2'

## Import ecoregions list ----
eco_list <- read_eco_list(here::here("data", "wildfinder", 
                                     "wildfinder-ecoregions_list.csv"))
```

```{r}
#| label: 'print-data-2'
#| echo: false

knitr::kable(head(eco_list), caption = "Content of the wildfinder-ecoregions_list file")
```


## Merging table

```{r}
#| label: 'read-data-3'

## Import merging table ----
sp_eco   <- read_sp_eco(here::here("data", "wildfinder", 
                                   "wildfinder-ecoregions_species.csv"))
```

```{r}
#| label: 'print-data-3'
#| echo: false

knitr::kable(head(sp_eco), caption = "Content of the wildfinder-ecoregions_species file")
```

# Species selection

```{r}
#| label: 'select-species'

## Select species ----
sp_list <- select_species(sp_list, family = params$"mammals_family")
```

```{r}
#| label: 'print-data-4'
#| echo: false

knitr::kable(sp_list, caption = paste("List of World", params$"mammals_family", "species"))
```

# Add ecoregions

```{r}
#| label: 'add-ecoregions'

## Add ecoregions to species list ----
sp_eco_list <- add_ecoregions(sp_list, sp_eco, eco_list)
```

```{r}
#| label: 'print-data-5'
#| echo: false

knitr::kable(head(sp_eco_list, 10), caption = paste("Complete dataset for", params$"mammals_family", "species"))
```

# Count ecoregions

```{r}
#| label: 'count-ecoregions'

## Count ecoregions by species ----
counts_data <- count_ecoregions(sp_eco_list)
```

```{r}
#| label: 'print-data-6'
#| echo: false

knitr::kable(counts_data, caption = paste("Number of ecoregions per", params$"mammals_family", "species"))
```

```{r}
#| label: 'plot-count'
#| out-width: '80%'
#| fig-cap: !expr paste("Number of ecoregions per", params$"mammals_family", "species")

## Barplot ----
plot_counts(counts_data)
```
